export const fines = [
  { desc: 'Ved ACE må man vælge en på modstanderholdet, som skal betale', price: '20,00 kr' },
  { desc: 'Død ved egen molotov', price: '10,00 kr' },
  { desc: 'Judas bøde (Team Kills)', price: '10,00 kr' },
  { desc: 'Afbud senere end 24 timer før', price: '50,00 kr' },
  { desc: 'Knife kills kr. 10,00 (den knifede betaler)', price: '10,00 kr' },
  { desc: 'Rage quits', price: '100,00 kr' },
  { desc: 'Møde for sent kr.', price: '10,00 kr + minutter' },
  { desc: 'Usportslig/ukammeratlig opførsel', price: '20,00 kr' },
  { desc: 'Medbringe egen salat', price: '5,00 kr' },
  { desc: 'Mobil ringer (m. lyd) under kamp', price: '20,00 kr' },
  { desc: 'Kysse iført spilledragten', price: '20,00 kr' },
  { desc: 'Tisse i badet', price: '30,00 kr' },
  { desc: 'Ynkelighedsbøde', price: '10,00 kr' },
  { desc: 'Bestille kurvand', price: '5,00 kr' },
  { desc: 'Nul kills i en halvleg', price: '1,00 kr' },
  { desc: 'Udeblivende betaling af bøde', price: '5,00 kr pr. dag' },
  { desc: 'Mere end 42 kills i et game (Aage bøde)', price: '20,00 kr' },
]
